paths: 
  /api/products:
    get:
      summary: Obtiene todos los productos.
      tags: 
        - Productos
      responses:
        "200":
          description: Respuesta exitosa, retorna un JSON de los productos
        "500":
          description: Error del servidor, no se pudieron obtener los productos